UPSTREAM: <carry>: openshift: OpenShift dockerfiles added

diff --git a/vendor/go.uber.org/atomic/Makefile b/vendor/go.uber.org/atomic/Makefile
--- a/vendor/go.uber.org/atomic/Makefile
+++ b/vendor/go.uber.org/atomic/Makefile
@@ -6,6 +6,7 @@ GOLINT = $(GOBIN)/golint
 <<<<<<< HEAD
 <<<<<<< HEAD
 <<<<<<< HEAD
+<<<<<<< HEAD
 GEN_ATOMICINT = $(GOBIN)/gen-atomicint
 GEN_ATOMICWRAPPER = $(GOBIN)/gen-atomicwrapper
 STATICCHECK = $(GOBIN)/staticcheck
@@ -248,3 +249,37 @@ generatenodirty:
 		echo "$$status"; \
 		echo "Please ensure that the generated code is up-to-date." )
 >>>>>>> 6b7ce455e (update vendored files)
+||||||| parent of 4a9b15dc1 (UPSTREAM: <carry>: openshift: OpenShift dockerfiles added)
+=======
+
+GO_FILES ?= *.go
+
+.PHONY: build
+build:
+	go build ./...
+
+.PHONY: test
+test:
+	go test -race ./...
+
+.PHONY: gofmt
+gofmt:
+	$(eval FMT_LOG := $(shell mktemp -t gofmt.XXXXX))
+	gofmt -e -s -l $(GO_FILES) > $(FMT_LOG) || true
+	@[ ! -s "$(FMT_LOG)" ] || (echo "gofmt failed:" && cat $(FMT_LOG) && false)
+
+$(GOLINT):
+	go install golang.org/x/lint/golint
+
+.PHONY: golint
+golint: $(GOLINT)
+	$(GOLINT) ./...
+
+.PHONY: lint
+lint: gofmt golint
+
+.PHONY: cover
+cover:
+	go test -coverprofile=cover.out -coverpkg ./... -v ./...
+	go tool cover -html=cover.out -o cover.html
+>>>>>>> 4a9b15dc1 (UPSTREAM: <carry>: openshift: OpenShift dockerfiles added)
